DROP TABLE IF EXISTS even_teams_users;

CREATE TABLE even_teams_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL,
  password TEXT NOT NULL,
  full_name TEXT NOT NULL
);

