DROP TABLE IF EXISTS even_teams_players;

CREATE TABLE even_teams_players (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  player_name TEXT NOT NULL,
  player_skill INTEGER NOT NULL,
  group_id INTEGER
    REFERENCES even_teams_groups(id) ON DELETE CASCADE NOT NULL 
);